[project]
name = "comfyui-noembryo"
description = """
A collection of nodes for ComyUI. \n
* "Load Image (from path)" is a node lets you load an image from any path in your computer or a URL, and use a selection rectangle at the preview to crop it. It can also
limit the output's size in megapixels. \n
* "H3 Motion Context Clip Stitcher" is a node that concatenates H3 Motion Context clip archives. \n
* "JsonPromptLoader" is a node that enhances a propt using a .json file with `item:prompt` pairs. \n
* "Resolution Scale" is a node that resizes an image using pixels or scale factor. \n
* "Regex Text Chopper" is a node that cuts text based on regex. \n
* "PromptTermList (1-6)" nodes to help with the creation of Prompts. \n
* "Auto Save Workflow" can save the current workflow to a .json file automatically. \n
"""
version = "1.6.2"
license = {text = "MIT License"}

[project.urls]
Repository = "https://github.com/noembryo/ComfyUI-noEmbryo"
#  Used by Comfy Registry https://comfyregistry.org

[tool.comfy]
PublisherId = "noembryo"
DisplayName = "noEmbryo"
Icon = "https://iili.io/JmSdmAJ.png"
